Vagrant.configure("2") do |config|

    config.vm.define "sequencer" do |cfg|
        cfg.vm.box = "geerlingguy/centos7"
        cfg.vm.network "private_network", ip: "10.0.2.10"
        cfg.vm.provision "shell", inline: <<-SHELL
            yum -q -y install java-1.8.0-openjdk
            java -version
            
            cd /vagrant
            nohup java -jar multi-server-1.0.0.jar sequencer 8080 http://10.0.2.11:8080 2> log-sequencer.err.txt 1> log-sequencer.txt &
            
        SHELL
    end
    
    config.vm.define "shuffler" do |cfg|
        cfg.vm.box = "geerlingguy/centos7"
        cfg.vm.network "private_network", ip: "10.0.2.11"
        cfg.vm.provision "shell", inline: <<-SHELL
            yum -q -y install java-1.8.0-openjdk
            java -version
            
            cd /vagrant
            nohup java -jar multi-server-1.0.0.jar shuffler 8080 http://10.0.2.12:8080 http://10.0.2.13:8080 2> log-shuffler.err.txt 1> log-shuffler.txt &
            
        SHELL
    end
    
    config.vm.define "server1" do |cfg|
        cfg.vm.box = "geerlingguy/centos7"
        cfg.vm.network "private_network", ip: "10.0.2.12"
        cfg.vm.provision "shell", inline: <<-SHELL
            yum -q -y install java-1.8.0-openjdk
            java -version
            
            cd /vagrant
            nohup java -jar multi-server-1.0.0.jar server 8080 2> log-server1.err.txt 1> log-server1.txt &
            
        SHELL
    end
    
    config.vm.define "server2" do |cfg|
        cfg.vm.box = "geerlingguy/centos7"
        cfg.vm.network "private_network", ip: "10.0.2.13"
        cfg.vm.provision "shell", inline: <<-SHELL
            yum -q -y install java-1.8.0-openjdk
            java -version
            
            cd /vagrant
            nohup java -jar multi-server-1.0.0.jar server 8080 2> log-server2.err.txt 1> log-server2.txt &
            
        SHELL
    end
  
end